FROM alpine:latest

WORKDIR /opt

COPY service.tar.gz ./

RUN apk add --update openssl libbz2 libtool libltdl libunistring libidn jansson libmicrohttpd gnutls sqlite-dev glib libgcrypt gmp flex bison && tar xvfz service.tar.gz && cp -r opt/* /usr && rm -rf service.tar.gz opt/ && rm -rf /var/cache/apk/* /tmp/*

EXPOSE 7777

COPY setup_reclaim.sh /opt

CMD [ "/opt/setup_reclaim.sh" ]

